export const GENRES_LIST = [
    {value: 1, label: 'MPB'},    
    {value: 2, label: 'POP'},
    {value: 3, label: 'TANGO'},    
    {value: 4, label: 'ROCK'},
    {value: 5, label: 'R&B'},    
    {value: 6, label: 'ELETRÔNICA'},
    {value: 7, label: 'TEEN'},    
    {value: 8, label: 'BLUES'},
    {value: 9, label: 'COUNTRY'},    
    {value: 10, label: 'FUNK'},
    {value: 11, label: 'HIP HOP'},    
    {value: 12, label: 'JAZZ'},
    {value: 13, label: 'PAGODE'},    
    {value: 14, label: 'SAMBA'},
    {value: 15, label: 'SERTANEJO'},    
    {value: 16, label: 'FORRÓ'},
    {value: 17, label: 'AXÉ'},
]