export const GENRES_LIST = [
  {   value: 'MPB', label: 'MPB' },    
  {   value: 'POP', label: 'POP' },
  {   value: 'TANGO', label: 'TANGO' },    
  {   value: 'ROCK', label: 'ROCK' },
  {   value: 'R&B', label: 'R&B' },    
  {   value: 'ELETRÔNICA', label: 'ELETRÔNICA' },
  {   value: 'TEEN', label: 'TEEN' },    
  {   value: 'BLUES', label: 'BLUES' },
  {   value: 'COUNTRY', label: 'COUNTRY' },    
  {   value: 'FUNK', label: 'FUNK' },
  {   value: 'HIP HOP', label: 'HIP HOP' },    
  {   value: 'JAZZ', label: 'JAZZ' },
  {   value: 'PAGODE', label: 'PAGODE' },    
  {   value: 'SAMBA', label: 'SAMBA' },
  {   value: 'SERTANEJO', label: 'SERTANEJO' },    
  {   value: 'FORRÓ', label: 'FORRÓ' },
  {   value: 'AXÉ', label: 'AXÉ' },
];
